
Style/AccessModifierIndentation:
  Description: Check indentation of private/protected visibility modifiers.
  StyleGuide: 'https://github.com/bbatsov/ruby-style-guide#indent-public-private-protected'
  Enabled: false

Style/AndOr:
  Description: 'Use &&/|| instead of and/or.'
  StyleGuide: 'https://github.com/bbatsov/ruby-style-guide#no-and-or-or'
  Enabled: false

Style/AlignParameters:
  Description: >-
                 Align the parameters of a method call if they span more
                 than one line.
  StyleGuide: 'https://github.com/bbatsov/ruby-style-guide#no-double-indent'
  Enabled: false

# Style/CaseIndentation:
#   Description: 'Indentation of when in a case/when/[else/]end.'
#   StyleGuide: 'https://github.com/bbatsov/ruby-style-guide#indent-when-to-case'
#   Enabled: true

Style/ClassVars:
  Description: 'Avoid the use of class variables.'
  StyleGuide: 'https://github.com/bbatsov/ruby-style-guide#no-class-vars'
  Enabled: false

# Style/ClosingParenthesisIndentation:
#   Description: 'Checks the indentation of hanging closing parentheses.'
#   Enabled: true

Style/CommentIndentation:
  Description: 'Indentation of comments.'
  Enabled: false

Style/EmptyLines:
  Description: "Don't use several empty lines in a row."
  Enabled: false

Style/ElseAlignment:
  Description: 'Align elses and elsifs correctly.'
  Enabled: false

Style/EmptyLiteral:
  Description: 'Prefer literals to Array.new/Hash.new/String.new.'
  StyleGuide: 'https://github.com/bbatsov/ruby-style-guide#literal-array-hash'
  Enabled: false

Style/FirstParameterIndentation:
  Description: 'Checks the indentation of the first parameter in a method call.'
  Enabled: false

# Style/InitialIndentation:
#   Description: >-
#     Checks the indentation of the first non-blank non-comment line in a file.
#   Enabled: true

# Style/IndentationConsistency:
#   Description: 'Keep indentation straight.'
#   Enabled: true

Style/IndentationWidth:
  Description: 'Use 2 spaces for indentation.'
  StyleGuide: 'https://github.com/bbatsov/ruby-style-guide#spaces-indentation'
  Enabled: false

Style/IndentArray:
  Description: >-
                 Checks the indentation of the first element in an array
                 literal.
  Enabled: false

Style/IndentAssignment:
  Description: >-
                 Checks the indentation of the first line of the
                 right-hand-side of a multi-line assignment.
  Enabled: false

Style/IndentHash:
  Description: 'Checks the indentation of the first key in a hash literal.'
  Enabled: false

# Style/MultilineMethodCallIndentation:
#   Description: >-
#                  Checks indentation of method calls with the dot operator
#                  that span more than one line.
#   Enabled: true

# Style/MultilineOperationIndentation:
#   Description: >-
#                  Checks indentation of binary operations that span more than
#                  one line.
#   Enabled: true

Style/Tab:
  Description: 'No hard tabs.'
  StyleGuide: 'https://github.com/bbatsov/ruby-style-guide#spaces-indentation'
  Enabled: false

Lint/EndAlignment:
  Description: 'Align ends correctly.'
  Enabled: false

Metrics/AbcSize:
  Description: >-
                 A calculated magnitude based on number of assignments,
                 branches, and conditions.
  Reference: 'http://c2.com/cgi/wiki?AbcMetric'
  Enabled: false

Metrics/ClassLength:
  Description: 'Avoid classes longer than 100 lines of code.'
  Enabled: false

Metrics/CyclomaticComplexity:
  Description: >-
                 A complexity metric that is strongly correlated to the number
                 of test cases needed to validate a method.
  Enabled: false

Metrics/PerceivedComplexity:
  Description: >-
                 A complexity metric geared towards measuring complexity for a
                 human reader.
  Enabled: false

Metrics/LineLength:
  Description: 'Limit lines to 100 characters.'
  Max: 100
  StyleGuide: 'https://github.com/bbatsov/ruby-style-guide#80-character-limits'
  Enabled: true

Metrics/MethodLength:
  Description: 'Avoid methods longer than 10 lines of code.'
  StyleGuide: 'https://github.com/bbatsov/ruby-style-guide#short-methods'
  Enabled: false

Metrics/ModuleLength:
  Description: 'Avoid modules longer than 100 lines of code.'
  Enabled: false